name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2


    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build app
      run: | 
        docker build . \
        --tag ghcr.io/$GITHUB_ACTOR/django-sozluk:latest \
        --push
